import { currentLedgerStore } from '../../lib/currentLedger';
import { createAccount, listAccounts, updateAccount, type Account } from '../../services/accounts';
import { activeEntries, currentMonth, parseYuanToCents } from '../../services/business-state';
import { archiveSharedResource, createAsset, createSnapshot, listAssets, listSnapshots, restoreSharedResource, updateAsset, type Asset, type AssetSnapshot } from '../../services/assets';
interface Data { accounts: Account[]; assets: Asset[]; snapshots: AssetSnapshot[]; selectedAssetId: number | null; form: 'account' | 'asset' | 'snapshot' | ''; editingId: number | null; name: string; value: string; kind: string; month: string; note: string; isOwner: boolean; loading: boolean; saving: boolean; errorMessage: string; }
interface PageContext { data: Data; setData(data: Partial<Data>): void; onShow(): Promise<void>; }
const errorText = (error: unknown, fallback: string) => error instanceof Error ? error.message : fallback;
const isOwner = () => currentLedgerStore.get()?.role === 'OWNER';
Page({
  data: { accounts: [], assets: [], snapshots: [], selectedAssetId: null, form: '', editingId: null, name: '', value: '', kind: '', month: currentMonth(), note: '', isOwner: false, loading: false, saving: false, errorMessage: '' },
  async onShow(): Promise<void> { const page = this as unknown as PageContext; page.setData({ loading: true, errorMessage: '', isOwner: isOwner() }); const [accounts, assets] = await Promise.allSettled([listAccounts(), listAssets()]); page.setData({ accounts: accounts.status === 'fulfilled' ? accounts.value : [], assets: assets.status === 'fulfilled' ? assets.value : [], errorMessage: accounts.status === 'rejected' || assets.status === 'rejected' ? '资产或账户加载失败' : '', loading: false }); },
  openAccount(): void { (this as unknown as PageContext).setData({ form: 'account', editingId: null, name: '', value: '', kind: '', errorMessage: '' }); },
  openAccountEdit(event: { currentTarget: { dataset: { id: string } } }): void { const page = this as unknown as PageContext; const item = page.data.accounts.find(({ id }) => id === Number(event.currentTarget.dataset.id)); page.setData({ form: 'account', editingId: item?.id ?? null, name: item?.name ?? '' }); },
  openAsset(): void { (this as unknown as PageContext).setData({ form: 'asset', editingId: null, name: '', value: '', kind: '', errorMessage: '' }); },
  openAssetEdit(event: { currentTarget: { dataset: { id: string } } }): void { const page = this as unknown as PageContext; const item = page.data.assets.find(({ id }) => id === Number(event.currentTarget.dataset.id)); if (item) page.setData({ form: 'asset', editingId: item.id, name: item.name, value: String((item.valueCents ?? 0) / 100), kind: item.kind ?? '' }); },
  async openSnapshot(event: { currentTarget: { dataset: { id: string } } }): Promise<void> { const page = this as unknown as PageContext; const item = page.data.assets.find(({ id }) => id === Number(event.currentTarget.dataset.id)); if (item && !item.archived) { page.setData({ form: 'snapshot', editingId: item.id, selectedAssetId: item.id, value: String((item.valueCents ?? 0) / 100), month: currentMonth(), note: '' }); try { page.setData({ snapshots: await listSnapshots(item.id) }); } catch (error) { page.setData({ errorMessage: errorText(error, '市值记录加载失败') }); } } },
  closeForm(): void { const page = this as unknown as PageContext; if (!page.data.saving) page.setData({ form: '', editingId: null }); },
  handleInput(event: { currentTarget: { dataset: { field: keyof Data } }; detail: { value: string } }): void { const page = this as unknown as PageContext; page.setData({ [event.currentTarget.dataset.field]: event.detail.value } as Partial<Data>); },
  async saveForm(): Promise<void> { const page = this as unknown as PageContext; if (page.data.saving) return; page.setData({ saving: true, errorMessage: '' }); try { if (page.data.form === 'account') { if (!page.data.name.trim()) throw new Error('请输入账户名称'); if (page.data.editingId === null) await createAccount(page.data.name); else await updateAccount(page.data.editingId, page.data.name); } else if (page.data.form === 'asset') { if (!page.data.name.trim() || parseYuanToCents(page.data.value) === null) throw new Error('请填写资产名称和有效市值'); if (page.data.editingId === null) await createAsset({ name: page.data.name, value: page.data.value, kind: page.data.kind }); else await updateAsset(page.data.editingId, { name: page.data.name, value: page.data.value, kind: page.data.kind }); } else if (page.data.form === 'snapshot' && page.data.editingId !== null) await createSnapshot(page.data.editingId, { month: page.data.month, value: page.data.value, note: page.data.note.trim() || null }); page.setData({ form: '' }); await page.onShow(); } catch (error) { page.setData({ errorMessage: errorText(error, '保存失败，请重试') }); } finally { page.setData({ saving: false }); } },
  async toggleArchive(event: { currentTarget: { dataset: { id: string; archived: string } } }): Promise<void> { const page = this as unknown as PageContext; if (!isOwner()) return; const id = Number(event.currentTarget.dataset.id); const archived = event.currentTarget.dataset.archived === 'true' || event.currentTarget.dataset.archived === '1'; try { if (archived) await restoreSharedResource('assets', id); else await archiveSharedResource('assets', id); await page.onShow(); } catch (error) { page.setData({ errorMessage: errorText(error, '状态更新失败') }); } },
  async toggleAccountArchive(event: { currentTarget: { dataset: { id: string; archived: string } } }): Promise<void> { const page = this as unknown as PageContext; if (!isOwner()) return; const id = Number(event.currentTarget.dataset.id); const archived = event.currentTarget.dataset.archived === 'true' || event.currentTarget.dataset.archived === '1'; try { if (archived) await restoreSharedResource('accounts', id); else await archiveSharedResource('accounts', id); await page.onShow(); } catch (error) { page.setData({ errorMessage: errorText(error, '状态更新失败') }); } },
  async showSnapshots(event: { currentTarget: { dataset: { id: string } } }): Promise<void> { const page = this as unknown as PageContext; const id = Number(event.currentTarget.dataset.id); try { page.setData({ selectedAssetId: id, snapshots: await listSnapshots(id) }); } catch (error) { page.setData({ errorMessage: errorText(error, '市值记录加载失败') }); } },
});
