import { currentLedgerStore } from '../../lib/currentLedger';
import { sessionStore } from '../../lib/session';
import { activeAccounts, listAccounts, type Account } from '../../services/accounts';
import { activeEntries, parseYuanToCents } from '../../services/business-state';
import { archiveSharedResource, canEditRepayment, createLiability, createRepayment, deleteRepayment, listLiabilities, listRepayments, restoreSharedResource, updateLiability, updateRepayment, type Liability, type Repayment } from '../../services/liabilities';
interface Data { liabilities: Liability[]; accounts: Account[]; repayments: Repayment[]; selectedId: number | null; form: 'liability' | 'repayment' | ''; editingId: number | null; name: string; remaining: string; monthlyPayment: string; paymentDay: string; amount: string; accountId: number | null; occurredOn: string; isOwner: boolean; confirmId: number | null; loading: boolean; saving: boolean; errorMessage: string; }
interface PageContext { data: Data; setData(data: Partial<Data>): void; onShow(): Promise<void>; }
const text = (error: unknown, fallback: string) => error instanceof Error ? error.message : fallback;
const owner = () => currentLedgerStore.get()?.role === 'OWNER';
Page({
  data: { liabilities: [], accounts: [], repayments: [], selectedId: null, form: '', editingId: null, name: '', remaining: '', monthlyPayment: '', paymentDay: '', amount: '', accountId: null, occurredOn: new Date().toISOString().slice(0, 10), isOwner: false, confirmId: null, loading: false, saving: false, errorMessage: '' },
  async onShow(): Promise<void> { const page = this as unknown as PageContext; page.setData({ loading: true, errorMessage: '', isOwner: owner() }); const [liabilities, accounts, repayments] = await Promise.allSettled([listLiabilities(), listAccounts(), listRepayments()]); const current = currentLedgerStore.get(); const userId = sessionStore.get()?.userId ?? -1; const repaymentItems = repayments.status === 'fulfilled' ? repayments.value.map((item) => ({ ...item, canEdit: Boolean(current && canEditRepayment(item, userId, current.role)) })) : []; page.setData({ liabilities: liabilities.status === 'fulfilled' ? liabilities.value : [], accounts: accounts.status === 'fulfilled' ? activeAccounts(accounts.value) : [], repayments: repaymentItems, errorMessage: [liabilities, accounts, repayments].some((result) => result.status === 'rejected') ? '负债数据加载失败' : '', loading: false }); },
  openCreate(): void { (this as unknown as PageContext).setData({ form: 'liability', editingId: null, name: '', remaining: '', monthlyPayment: '', paymentDay: '', errorMessage: '' }); },
  openEdit(event: { currentTarget: { dataset: { id: string } } }): void { const page = this as unknown as PageContext; const item = page.data.liabilities.find(({ id }) => id === Number(event.currentTarget.dataset.id)); if (item) page.setData({ form: 'liability', editingId: item.id, name: item.name, remaining: String((item.remainingCents ?? 0) / 100), monthlyPayment: String((item.monthlyPaymentCents ?? 0) / 100), paymentDay: item.paymentDay ? String(item.paymentDay) : '' }); },
  openRepayment(event: { currentTarget: { dataset: { id: string } } }): void { const page = this as unknown as PageContext; const item = page.data.liabilities.find(({ id }) => id === Number(event.currentTarget.dataset.id)); const account = page.data.accounts.find(({ isDefault }) => Boolean(isDefault)); if (item && !item.archived) page.setData({ selectedId: item.id, form: 'repayment', editingId: null, amount: String((item.monthlyPaymentCents ?? 0) / 100), accountId: account?.id ?? null, occurredOn: new Date().toISOString().slice(0, 10) }); },
  selectLiability(event: { currentTarget: { dataset: { id: string } } }): void { (this as unknown as PageContext).setData({ selectedId: Number(event.currentTarget.dataset.id) }); },
  editRepayment(event: { currentTarget: { dataset: { id: string } } }): void { const page = this as unknown as PageContext; const repayment = page.data.repayments.find(({ id }) => id === Number(event.currentTarget.dataset.id)); const liability = repayment && page.data.liabilities.find(({ id }) => id === repayment.liability_id); const current = currentLedgerStore.get(); if (repayment && liability && current && canEditRepayment(repayment, sessionStore.get()?.userId ?? -1, current.role)) page.setData({ selectedId: liability.id, form: 'repayment', editingId: repayment.id, amount: String(repayment.amount_cents / 100), accountId: repayment.account_id ?? null, occurredOn: repayment.occurred_on }); },
  requestDeleteRepayment(event: { currentTarget: { dataset: { id: string } } }): void { const page = this as unknown as PageContext; const repayment = page.data.repayments.find(({ id }) => id === Number(event.currentTarget.dataset.id)); const current = currentLedgerStore.get(); if (repayment && current && canEditRepayment(repayment, sessionStore.get()?.userId ?? -1, current.role)) page.setData({ confirmId: repayment.id }); },
  async confirmDelete(): Promise<void> { const page = this as unknown as PageContext; if (page.data.confirmId === null) return; page.setData({ saving: true }); try { await deleteRepayment(page.data.confirmId); page.setData({ confirmId: null }); await page.onShow(); } catch (error) { page.setData({ errorMessage: text(error, '删除还款失败') }); } finally { page.setData({ saving: false }); } },
  cancelDelete(): void { (this as unknown as PageContext).setData({ confirmId: null }); }, closeForm(): void { const page = this as unknown as PageContext; if (!page.data.saving) page.setData({ form: '', editingId: null }); },
  handleInput(event: { currentTarget: { dataset: { field: keyof Data } }; detail: { value: string } }): void { const page = this as unknown as PageContext; page.setData({ [event.currentTarget.dataset.field]: event.detail.value } as Partial<Data>); },
  handleAccount(event: { detail: { value: string } }): void { (this as unknown as PageContext).setData({ accountId: Number(event.detail.value) }); },
  async saveForm(): Promise<void> { const page = this as unknown as PageContext; if (page.data.saving) return; page.setData({ saving: true, errorMessage: '' }); try { if (page.data.form === 'liability') { const remaining = parseYuanToCents(page.data.remaining); const monthly = parseYuanToCents(page.data.monthlyPayment || '0'); const day = page.data.paymentDay.trim() ? Number(page.data.paymentDay) : undefined; if (!page.data.name.trim() || remaining === null || remaining < 0 || monthly === null || monthly < 0) throw new Error('请填写有效的负债金额'); if (day !== undefined && (!Number.isInteger(day) || day < 1 || day > 31)) throw new Error('还款日需为 1-31'); if (page.data.editingId === null) await createLiability({ name: page.data.name, remaining: page.data.remaining, monthlyPayment: page.data.monthlyPayment || '0', ...(day === undefined ? {} : { paymentDay: day }) }); else await updateLiability(page.data.editingId, { name: page.data.name, remaining: page.data.remaining, monthlyPayment: page.data.monthlyPayment || '0', paymentDay: day ?? null }); } else if (page.data.form === 'repayment' && page.data.selectedId !== null && page.data.accountId !== null) { const liability = page.data.liabilities.find(({ id }) => id === page.data.selectedId); const account = activeEntries(page.data.accounts).some(({ id }) => id === page.data.accountId); const amount = parseYuanToCents(page.data.amount); const old = page.data.editingId === null ? 0 : page.data.repayments.find(({ id }) => id === page.data.editingId)?.amount_cents ?? 0; if (!liability || liability.archived || !account || amount === null || amount <= 0 || amount > (liability.remainingCents ?? 0) + old) throw new Error('还款金额必须为正数且不能超过剩余本金'); const payload = { liabilityId: liability.id, amount: page.data.amount, accountId: page.data.accountId, occurredOn: page.data.occurredOn }; if (page.data.editingId === null) await createRepayment(payload); else await updateRepayment(page.data.editingId, payload); } page.setData({ form: '' }); await page.onShow(); } catch (error) { page.setData({ errorMessage: text(error, '保存失败，请重试') }); } finally { page.setData({ saving: false }); } },
  async toggleArchive(event: { currentTarget: { dataset: { id: string; archived: string } } }): Promise<void> { const page = this as unknown as PageContext; if (!owner()) return; const id = Number(event.currentTarget.dataset.id); const archived = event.currentTarget.dataset.archived === 'true' || event.currentTarget.dataset.archived === '1'; try { if (archived) await restoreSharedResource('liabilities', id); else await archiveSharedResource('liabilities', id); await page.onShow(); } catch (error) { page.setData({ errorMessage: text(error, '状态更新失败') }); } },
});
