import { currentLedgerStore } from '../../lib/currentLedger';
import { sessionStore } from '../../lib/session';
import { activeAccounts, listAccounts, type Account } from '../../services/accounts';
import { activeEntries, currentMonth, parseYuanToCents } from '../../services/business-state';
import { createCategory, listCategories, type Category } from '../../services/categories';
import { canDeleteTransaction, canEditTransaction, createTransaction, deleteTransaction, isGeneratedRepaymentTransaction, listTransactions, updateTransaction, type TransactionRecord, type TransactionType } from '../../services/transactions';

interface Draft { type: TransactionType; amount: string; accountId: number | null; toAccountId: number | null; categoryId: number | null; occurredOn: string; note: string; }
interface Data { month: string; typeFilter: string; items: TransactionRecord[]; accounts: Account[]; expenseCategories: Category[]; incomeCategories: Category[]; draft: Draft; newCategoryName: string; editingId: number | null; formOpen: boolean; selected: TransactionRecord | null; selectedGenerated: boolean; selectedCanEdit: boolean; selectedCanDelete: boolean; confirmId: number | null; loading: boolean; saving: boolean; errorMessage: string; referenceError: string; }
interface PageContext { data: Data; setData(data: Partial<Data>): void; onShow(): Promise<void>; }
function msg(error: unknown, fallback: string): string { return error instanceof Error ? error.message : fallback; }
function emptyDraft(): Draft { return { type: 'expense', amount: '', accountId: null, toAccountId: null, categoryId: null, occurredOn: new Date().toISOString().slice(0, 10), note: '' }; }
function currentUserCan(record: TransactionRecord, action: 'edit' | 'delete'): boolean { const ledger = currentLedgerStore.get(); const allowed = ledger ? (action === 'edit' ? canEditTransaction : canDeleteTransaction) : () => false; return Boolean(ledger && allowed(record, sessionStore.get()?.userId ?? -1, ledger.role)); }

Page({
  data: { month: currentMonth(), typeFilter: '', items: [], accounts: [], expenseCategories: [], incomeCategories: [], draft: emptyDraft(), newCategoryName: '', editingId: null, formOpen: false, selected: null, selectedGenerated: false, selectedCanEdit: false, selectedCanDelete: false, confirmId: null, loading: false, saving: false, errorMessage: '', referenceError: '' },
  async onShow(): Promise<void> {
    const page = this as unknown as PageContext; page.setData({ loading: true, errorMessage: '', referenceError: '' });
    const [transactions, accounts, expenses, incomes] = await Promise.allSettled([listTransactions({ month: page.data.month, type: page.data.typeFilter as TransactionType || undefined }), listAccounts(), listCategories('expense'), listCategories('income')]);
    const errors: string[] = [];
    if (transactions.status === 'fulfilled') page.setData({ items: (transactions.value as { items?: TransactionRecord[] }).items ?? [] }); else errors.push('交易加载失败');
    if (accounts.status === 'fulfilled') page.setData({ accounts: activeAccounts(accounts.value) }); else errors.push('账户加载失败');
    if (expenses.status === 'fulfilled') page.setData({ expenseCategories: activeEntries(expenses.value) }); else errors.push('支出分类加载失败');
    if (incomes.status === 'fulfilled') page.setData({ incomeCategories: activeEntries(incomes.value) }); else errors.push('收入分类加载失败');
    page.setData({ referenceError: errors.join('；'), loading: false });
  },
  handleMonthInput(event: { detail: { value: string } }): void { const page = this as unknown as PageContext; page.setData({ month: event.detail.value }); void page.onShow(); },
  handleTypeFilter(event: { detail: { value: string } }): void { const page = this as unknown as PageContext; page.setData({ typeFilter: ['', 'expense', 'income', 'transfer'][Number(event.detail.value)] ?? '' }); void page.onShow(); },
  openCreate(): void { (this as unknown as PageContext).setData({ draft: emptyDraft(), newCategoryName: '', editingId: null, formOpen: true, errorMessage: '' }); },
  openDetail(event: { currentTarget: { dataset: { id: string } } }): void { const page = this as unknown as PageContext; const selected = page.data.items.find(({ id }) => id === Number(event.currentTarget.dataset.id)) ?? null; page.setData({ selected, selectedGenerated: selected ? isGeneratedRepaymentTransaction(selected) : false, selectedCanEdit: selected ? currentUserCan(selected, 'edit') : false, selectedCanDelete: selected ? currentUserCan(selected, 'delete') : false }); },
  closeDetail(): void { (this as unknown as PageContext).setData({ selected: null, selectedGenerated: false, selectedCanEdit: false, selectedCanDelete: false }); },
  openEdit(): void { const page = this as unknown as PageContext; const item = page.data.selected; if (!item || !currentUserCan(item, 'edit')) return; page.setData({ selected: null, editingId: item.id, formOpen: true, draft: { type: item.type, amount: String((item.amountCents ?? 0) / 100), accountId: item.accountId ?? null, toAccountId: item.toAccountId ?? null, categoryId: item.categoryId ?? null, occurredOn: item.occurredOn ?? page.data.month + '-01', note: item.note ?? '' } }); },
  requestDelete(): void { const page = this as unknown as PageContext; if (page.data.selected && currentUserCan(page.data.selected, 'delete')) page.setData({ confirmId: page.data.selected.id, selected: null }); },
  async confirmDelete(): Promise<void> { const page = this as unknown as PageContext; if (page.data.confirmId === null) return; page.setData({ saving: true }); try { await deleteTransaction(page.data.confirmId); page.setData({ confirmId: null }); await page.onShow(); } catch (error) { page.setData({ errorMessage: msg(error, '删除失败，请重试') }); } finally { page.setData({ saving: false }); } },
  cancelDelete(): void { (this as unknown as PageContext).setData({ confirmId: null }); },
  closeForm(): void { const page = this as unknown as PageContext; if (!page.data.saving) page.setData({ formOpen: false }); },
  handleDraftInput(event: { currentTarget: { dataset: { field: keyof Draft } }; detail: { value: string } }): void { const page = this as unknown as PageContext; page.setData({ draft: { ...page.data.draft, [event.currentTarget.dataset.field]: event.detail.value } }); },
  handleTypeInput(event: { detail: { value: string } }): void { const page = this as unknown as PageContext; page.setData({ draft: { ...page.data.draft, type: (['expense', 'income', 'transfer'][Number(event.detail.value)] ?? 'expense') as TransactionType, categoryId: null, toAccountId: null } }); },
  handleAccountInput(event: { detail: { value: string } }): void { const page = this as unknown as PageContext; page.setData({ draft: { ...page.data.draft, accountId: Number(event.detail.value) } }); },
  handleToAccountInput(event: { detail: { value: string } }): void { const page = this as unknown as PageContext; page.setData({ draft: { ...page.data.draft, toAccountId: Number(event.detail.value) } }); },
  handleCategoryInput(event: { detail: { id: number } }): void { const page = this as unknown as PageContext; page.setData({ draft: { ...page.data.draft, categoryId: event.detail.id } }); },
  handleCategoryName(event: { detail: { value: string } }): void { (this as unknown as PageContext).setData({ newCategoryName: event.detail.value }); },
  async saveNewCategory(): Promise<void> { const page = this as unknown as PageContext; if (!page.data.newCategoryName.trim() || page.data.saving || page.data.draft.type === 'transfer') return; page.setData({ saving: true, errorMessage: '' }); try { const category = await createCategory(page.data.draft.type, page.data.newCategoryName); page.setData({ newCategoryName: '', draft: { ...page.data.draft, categoryId: category.id } }); await page.onShow(); } catch (error) { page.setData({ errorMessage: msg(error, '分类创建失败') }); } finally { page.setData({ saving: false }); } },
  async saveForm(): Promise<void> { const page = this as unknown as PageContext; const draft = page.data.draft; const cents = parseYuanToCents(draft.amount); if (page.data.saving) return; if (cents === null || cents <= 0) { page.setData({ errorMessage: '请输入正数金额' }); return; } if (!draft.accountId || (draft.type === 'transfer' && (!draft.toAccountId || draft.accountId === draft.toAccountId))) { page.setData({ errorMessage: '请选择不同的转出和转入账户' }); return; } page.setData({ saving: true, errorMessage: '' }); try { const input = { type: draft.type, amount: draft.amount, accountId: draft.accountId, ...(draft.type === 'transfer' ? { toAccountId: draft.toAccountId! } : draft.categoryId ? { categoryId: draft.categoryId } : {}), occurredOn: draft.occurredOn, note: draft.note.trim() }; if (page.data.editingId === null) await createTransaction(input); else await updateTransaction(page.data.editingId, input); page.setData({ formOpen: false }); await page.onShow(); } catch (error) { page.setData({ errorMessage: msg(error, '保存失败，请重试') }); } finally { page.setData({ saving: false }); } },
});
