import { currentMonth } from '../../services/business-state';
import { currentLedgerStore } from '../../lib/currentLedger';
import { getCategoryBreakdown, getMonthlySnapshot, getMonthlyTrend, getSummary, type StatisticsSummary } from '../../services/statistics';
interface Trend { month: string; label?: string; incomeCents?: number; expenseCents?: number; netCents?: number; income?: string; expense?: string; net?: string; incomeHeight?: number; expenseHeight?: number; }
interface Breakdown { categoryId: number; name: string; cents?: number; percent?: number; amount?: string; }
interface Snapshot { incomeCents?: number; expenseCents?: number; netCents?: number; netWorthCents?: number; income?: string; expense?: string; net?: string; }
interface Data { ledgerName: string; switcherOpen: boolean; month: string; summary: StatisticsSummary | null; trend: Trend[]; breakdown: Breakdown[]; snapshot: Snapshot | null; loading: boolean; errorMessage: string; }
interface PageContext { data: Data; setData(data: Partial<Data>): void; onShow(): Promise<void>; }
Page({ data: { ledgerName: '我的账本', switcherOpen: false, month: currentMonth(), summary: null, trend: [], breakdown: [], snapshot: null, loading: false, errorMessage: '' }, async onShow(): Promise<void> { const page = this as unknown as PageContext; page.setData({ loading: true, errorMessage: '', ledgerName: currentLedgerStore.get()?.name ?? '我的账本' }); try { const [summary, trend, snapshot, breakdown] = await Promise.all([getSummary(), getMonthlyTrend(6, page.data.month), getMonthlySnapshot(page.data.month), getCategoryBreakdown(page.data.month)]); const max = Math.max(1, ...(trend as Trend[]).flatMap((item) => [item.incomeCents ?? 0, item.expenseCents ?? 0])); const readableTrend = (trend as Trend[]).map((item) => ({ ...item, label: item.month.slice(5) + '月', income: item.income ?? String((item.incomeCents ?? 0) / 100), expense: item.expense ?? String((item.expenseCents ?? 0) / 100), net: String((item.netCents ?? 0) / 100), incomeHeight: Math.max(4, Math.round((item.incomeCents ?? 0) / max * 100)), expenseHeight: Math.max(4, Math.round((item.expenseCents ?? 0) / max * 100)) })); page.setData({ summary, trend: readableTrend, snapshot: snapshot as Snapshot, breakdown: (breakdown as Breakdown[]).map((item) => ({ ...item, amount: ((item.cents ?? 0) / 100).toFixed(2) })) }); } catch (error) { page.setData({ errorMessage: error instanceof Error ? error.message : '分析数据加载失败' }); } finally { page.setData({ loading: false }); } }, openLedgerSwitcher(): void { (this as unknown as PageContext).setData({ switcherOpen: true }); }, closeLedgerSwitcher(): void { (this as unknown as PageContext).setData({ switcherOpen: false }); }, handleMonthInput(event: { detail: { value: string } }): void { const page = this as unknown as PageContext; page.setData({ month: event.detail.value }); void page.onShow(); }, todayMonth(): string { return currentMonth(); } });
